import { useEffect, useState, type FormEvent } from 'react'
import { Routes, Route, NavLink, Link, useParams } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { authClient, dataClient, restore, errorMessage } from './api/http'
import { useAuth } from './store/auth'
import type { Student, Meeting } from './types'
import { Planning } from './Planning'
import { Recorder } from './Recorder'
import { Dashboard } from './Dashboard'
import { Management, Sharing } from './Management'
import { HebrewDateTimeField } from './DateFields'
function ErrorBox({error}:{error:unknown}) {return error?<p role="alert" className="error">{errorMessage(error)}</p>:null}
function Login(){
 const [error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError(null);const f=new FormData(e.currentTarget);try{const {data}=await authClient.post('/login',{email:f.get('email'),password:f.get('password'),otp:f.get('otp')});useAuth.getState().set(data.accessToken,data.user)}catch(err){setError(err)}finally{setBusy(false)}}
 return <main className="login"><div className="login-intro"><span className="login-wordmark">◈ מרחב</span><h2>הקשבה יוצרת<br/>מקום לצמוח.</h2><p>מרחב אישי ליועצת בית הספר.<br/>תלמידות, פגישות ורצף ליווי — יחד.</p><div className="intro-circles" aria-hidden="true"><span/><span/><span/></div><small>כל תלמידה היא עולם.</small></div><section className="card"><span className="eyebrow">מרחב • ייעוץ בית ספרי</span><h1>ברוכה הבאה<br/>למרחב שלך.</h1><p>כניסה למערכת הפנימית של היועצת</p><form onSubmit={submit}><label>כתובת מייל<input name="email" type="email" autoComplete="username" required dir="ltr"/></label><label>סיסמה<input name="password" type="password" autoComplete="current-password" required dir="ltr"/></label><label>קוד אימות, אם הופעל<input name="otp" autoComplete="one-time-code" dir="ltr" maxLength={64} placeholder="קוד מהאפליקציה או קוד שחזור"/></label><ErrorBox error={error}/><button disabled={busy}>{busy?'מתחברת…':'כניסה למרחב'}</button></form><small>הגישה מיועדת למשתמשות מורשות בלבד.</small></section></main>
}
function useStudents(){return useQuery({queryKey:['students'],queryFn:async()=>(await dataClient.get<Student[]>('/students')).data})}
function Students(){const q=useStudents(),qc=useQueryClient();const [search,setSearch]=useState(''),[open,setOpen]=useState(false)
 const add=useMutation({mutationFn:async(body:object)=>dataClient.post('/students',body),onSuccess:()=>{qc.invalidateQueries({queryKey:['students']});setOpen(false)}})
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);add.mutate(Object.fromEntries(f))}
 return <><header className="row"><div><span className="eyebrow">ליווי אישי</span><h1>התלמידות שלי</h1><p>כרטיס אישי, רצף פגישות ותמונה מלאה.</p></div><button onClick={()=>{add.reset();setOpen(!open)}}>{open?'סגירה':'+ תלמידה חדשה'}</button></header>{open&&<form className="card" onSubmit={submit}><h2>הוספת תלמידה</h2><label>שם מלא<input name="name" maxLength={120} required/></label><label>כיתה<input name="classroom" maxLength={40} required/></label><label>סיבת הפניה<textarea name="referral" maxLength={4000}/></label><ErrorBox error={add.error}/><button disabled={add.isPending}>שמירת כרטיס</button></form>}<label className="search">חיפוש תלמידה<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="שם או כיתה"/></label><ErrorBox error={q.error}/>{q.isPending?<p>טוענת תלמידות…</p>:<div className="grid">{q.data?.filter(s=>(s.name+' '+s.classroom).includes(search)).map(s=><Link className="card student" key={s.id} to={'/students/'+s.id}><div className="student-top"><span className="avatar">{s.name[0]}</span><span className="student-arrow">↖</span></div><h2>{s.name}</h2><p>כיתה {s.classroom} • כרטיס אישי</p><span className="badge">{s.can_edit===false?'משותף לצפייה':s.archived?'בארכיון':'בליווי'}</span></Link>)}</div>}{q.data?.length===0&&<section className="card"><h2>כאן יתחיל הליווי</h2><p>הוסיפי תלמידה כדי ליצור כרטיס ראשון.</p></section>}</>}
function StudentPage(){const [dateError,setDateError]=useState('');const {id}=useParams();const students=useStudents();const s=students.data?.find(x=>x.id===id);const qc=useQueryClient();const q=useQuery({queryKey:['meetings',id],queryFn:async()=>(await dataClient.get<Meeting[]>(`/students/${id}/meetings`)).data});const [open,setOpen]=useState(false),[notes,setNotes]=useState(''),[summary,setSummary]=useState(''),[aiUsed,setAiUsed]=useState(false),[reviewed,setReviewed]=useState(false),[recordingBusy,setRecordingBusy]=useState(false)
 const add=useMutation({mutationFn:async(body:object)=>dataClient.post(`/students/${id}/meetings`,body),onSuccess:()=>{qc.invalidateQueries({queryKey:['meetings',id]});setOpen(false)}})
 const archive=useMutation({mutationFn:()=>dataClient.post(`/students/${id}/archive`),onSuccess:()=>qc.invalidateQueries({queryKey:['students']})})
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setDateError('');const f=new FormData(e.currentTarget);const raw=String(f.get('starts_at')||'');const start=new Date(raw);if(!raw||!Number.isFinite(start.getTime())){setDateError('יש לבחור תאריך ושעה לפגישה');return}add.mutate({starts_at:start.toISOString(),notes,summary,ai_assisted:aiUsed,consent_recorded:aiUsed,ai_reviewed:reviewed})}
 return <><Link to="/students">← חזרה לתלמידות</Link><header className="row"><div><span className="eyebrow">כרטיס תלמידה</span><h1>{s?.name??'כרטיס תלמידה'}</h1><p>{s&&`כיתה ${s.classroom} • ${s.archived?'בארכיון':'בליווי'}`}</p></div>{s&&s.can_edit!==false&&!s.archived&&<button onClick={()=>{if(recordingBusy)return;add.reset();setNotes('');setSummary('');setAiUsed(false);setReviewed(false);setOpen(!open)}} disabled={recordingBusy}>+ תיעוד פגישה</button>}</header><ErrorBox error={students.error}/><ErrorBox error={q.error}/>{s&&<section className="card"><h2>סיבת הפניה</h2><p className="pre">{s.referral||'לא הוזנה סיבת הפניה'}</p>{s.can_edit!==false&&!s.archived&&<button className="secondary" disabled={archive.isPending} onClick={()=>{if(window.confirm('להעביר את הכרטיס לארכיון? התיעוד יישמר.'))archive.mutate()}}>העברה לארכיון</button>}<ErrorBox error={archive.error}/></section>}{open&&<form className="card" onSubmit={submit}><h2>תיעוד מפגש</h2><HebrewDateTimeField name="starts_at" label="מועד הפגישה"/><label>תיעוד והערות<textarea name="notes" rows={6} maxLength={20000} value={notes} onChange={e=>{setNotes(e.target.value);setReviewed(false)}}/></label><label>סיכום וצעדי המשך<textarea name="summary" rows={4} maxLength={10000} value={summary} onChange={e=>{setSummary(e.target.value);setReviewed(false)}}/></label>{id&&<Recorder studentId={id} onBusy={setRecordingBusy} onTranscript={text=>{setNotes(text);setSummary('');setAiUsed(true);setReviewed(false)}} onSummary={text=>{setSummary(text);setAiUsed(true);setReviewed(false)}}/>}{aiUsed&&<label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> בדקתי ותיקנתי את התמלול ואת טיוטת הסיכום ומאשרת את התיעוד</label>}<ErrorBox error={add.error}/>{dateError&&<p className="error" role="alert">{dateError}</p>}<button disabled={add.isPending||recordingBusy||(aiUsed&&!reviewed)}>שמירת פגישה</button></form>}{s?.can_edit===false&&<p className="card">כרטיס משותף לצפייה בלבד.</p>}{s&&s.can_edit!==false&&<Sharing studentId={s.id}/ >}{s&&<Planning key={s.id} kind="tasks" studentId={s.id} readOnly={s.can_edit===false}/>}<h2>רצף הפגישות</h2>{q.isPending?<p>טוענת פגישות…</p>:q.data?.length===0?<section className="card">עדיין אין פגישות מתועדות.</section>:q.data?.map(m=><article className="card meeting" key={m.id}><time>{new Date(m.starts_at).toLocaleString('he-IL')}</time>{m.ai_assisted&&<span className="badge">תיעוד בסיוע AI • נבדק ואושר</span>}<h3>תיעוד המפגש</h3><p className="pre">{m.notes||'ללא הערות'}</p><h3>סיכום וצעדי המשך</h3><p className="pre">{m.summary||'ללא סיכום'}</p></article>)}</>
}
export default function App(){const user=useAuth(x=>x.user),qc=useQueryClient();const [ready,setReady]=useState(false),[error,setError]=useState<unknown>(null)
 useEffect(()=>{restore().finally(()=>setReady(true))},[])
 useEffect(()=>{if(!user)qc.clear()},[user,qc])
 useEffect(()=>{if(!user)return;let timer:ReturnType<typeof setTimeout>;const reset=()=>{clearTimeout(timer);timer=setTimeout(()=>{useAuth.getState().clear();qc.clear();authClient.post('/logout').catch(()=>{})},15*60*1000)};const events=['pointerdown','keydown','touchstart'];events.forEach(e=>window.addEventListener(e,reset));reset();return()=>{clearTimeout(timer);events.forEach(e=>window.removeEventListener(e,reset))}},[user,qc])
 async function logout(){setError(null);try{await authClient.post('/logout');useAuth.getState().clear();qc.clear()}catch(err){setError(err)}}
 if(!ready)return <main className="login">פותחת את המרחב…</main>
 if(!user)return <Login/>
 return <div className="shell"><aside><Link className="brand" to="/"><span className="brand-symbol">◈</span> מרחב<span className="brand-subtitle">ייעוץ בית ספרי</span></Link><nav><NavLink to="/" end><span className="nav-icon">◫</span>מבט על</NavLink><NavLink to="/students"><span className="nav-icon">◉</span>תלמידות</NavLink><NavLink to="/calendar"><span className="nav-icon">▦</span>יומן פגישות</NavLink><NavLink to="/tasks"><span className="nav-icon">✓</span>משימות</NavLink><NavLink to="/settings"><span className="nav-icon">⚙</span>הגדרות</NavLink></nav><div className="sidebar-note"><span>✦</span><strong>מקום להקשבה</strong><p>לתעד, ללוות ולראות<br/>את הדרך שנעשתה.</p></div><div className="account"><span className="account-avatar">{user.name[0]}</span><strong>{user.name}</strong><small>מרחב אישי ליועצת</small><button className="secondary" onClick={logout}>יציאה מהמערכת</button><ErrorBox error={error}/></div></aside><main className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/students" element={<Students/>}/><Route path="/students/:id" element={<StudentPage/>}/><Route path="/calendar" element={<Planning kind="appointments"/>}/><Route path="/tasks" element={<Planning kind="tasks"/>}/><Route path="/settings" element={<Management/>}/><Route path="*" element={<><h1>העמוד לא נמצא</h1><Link to="/">חזרה למבט על</Link></>}/></Routes><footer>מרחב אישי • הקשבה, תיעוד ורצף ליווי</footer></main></div>
}
