import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { dataClient, errorMessage } from './api/http'
import { useAuth } from './store/auth'
import { AISettings } from './AISettings'
function fields(form:HTMLFormElement){return Object.fromEntries(new FormData(form)) as Record<string,string>}
export function Proof(){return <fieldset className="proof"><legend>אישור פעולה רגישה</legend><label>הסיסמה שלך<input name="password" type="password" autoComplete="current-password" required maxLength={256}/></label><label>קוד אימות, אם הופעל<input name="otp" autoComplete="one-time-code" dir="ltr" maxLength={64} placeholder="קוד מהאפליקציה או קוד שחזור"/></label></fieldset>}
export function Action({children,run,button='שמירה',requireProof=true}:{children:React.ReactNode;run:(form:HTMLFormElement)=>Promise<string|void>;button?:string;requireProof?:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState<unknown>(null)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError(null);setMessage('');try{const msg=await run(form);setMessage(msg||'הפעולה הושלמה');form.querySelectorAll<HTMLInputElement>('input[type=password], input[name=otp]').forEach(i=>i.value='')}catch(err){setError(err)}finally{setBusy(false)}}
 return <form onSubmit={submit}>{children}{requireProof&&<Proof/>}{!!error&&<p role="alert" className="error">{errorMessage(error)}</p>}{message&&<p role="status" className="success">{message}</p>}<button disabled={busy}>{busy?'מבצעת…':button}</button></form>
}
function download(content:string,filename:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
type Security={mfa_enabled:boolean;role:string;recovery_remaining:number;last_backup:string|null;email_verified:boolean;email_connected:boolean}
function SecurityPanel({info}:{info:Security}){
 const [setup,setSetup]=useState<{secret:string;uri:string}|null>(null),[codes,setCodes]=useState<string[]>([]);const qc=useQueryClient()
 function leave(){useAuth.getState().clear();qc.clear()}
 return <section className="card"><span className="eyebrow">כניסה מוגנת</span><h2>אבטחת החשבון</h2><p>כתובת המייל: {info.email_verified?'מאומתת':'טרם אומתה'}</p>{!info.email_verified&&info.email_connected&&<Action requireProof={false} button="שליחת מייל אימות" run={async()=>{return (await dataClient.post('/account/verify/request')).data.message}}><p>קישור האימות יישלח לכתובת המייל של החשבון.</p></Action>}<h3>אימות דו־שלבי</h3>{codes.length>0?<><p>האימות הופעל. שמרי את קודי השחזור במקום מוגן לפני הכניסה מחדש. כל קוד תקף פעם אחת. בכניסה מחדש השתמשי בקוד הבא שיופיע באפליקציה.</p><div className="recovery-codes" dir="ltr">{codes.map(c=><code key={c}>{c}</code>)}</div><button type="button" onClick={()=>download(codes.join('\n'),'merhav-recovery-codes.txt','text/plain')}>הורדת קודי שחזור</button><button className="secondary" onClick={leave}>שמרתי — כניסה מחדש</button></>:info.mfa_enabled?<><p>האימות פעיל. נותרו {info.recovery_remaining} קודי שחזור.</p><Action button="כיבוי אימות דו־שלבי" run={async form=>{await dataClient.post('/settings/mfa/disable',fields(form));leave()}}><p>כיבוי האימות ינתק את כל ההתחברויות שלך.</p></Action></>:<><p>חברי אפליקציית אימות כמו Google Authenticator או Microsoft Authenticator. הקוד מתחלף כל 30 שניות.</p>{!setup?<Action button="התחלת הגדרה" run={async form=>{setSetup((await dataClient.post('/settings/mfa/setup',fields(form))).data)}}><p>נדרש אישור הסיסמה לפני הצגת מפתח ההגדרה.</p></Action>:<><p>באפליקציית האימות הוסיפי חשבון ידנית עם המפתח הבא. בחרי קוד מבוסס זמן. ההגדרה תקפה ל־10 דקות.</p><code className="mfa-secret" dir="ltr">{setup.secret}</code><Action button="אישור והפעלת האימות" run={async form=>{const {data}=await dataClient.post('/settings/mfa/confirm',fields(form));setSetup(null);setCodes(data.recovery_codes)}}><p>הזיני למטה את הסיסמה שלך ואת הקוד שמופיע באפליקציה. לאחר האישור תידרש כניסה מחדש.</p></Action><button className="secondary" onClick={()=>setSetup(null)}>התחלה מחדש</button></>}</>}</section>
}
type Provider={id:string;name:string;enabled:boolean;configured:boolean;preferred:boolean;transcription_model:string;summary_model:string}
function ProviderForm({p}:{p:Provider}){
 const qc=useQueryClient()
 return <section className="card"><h3>{p.name}</h3><span className="badge">{p.configured?'מפתח אישי שמור':'אין מפתח אישי'}</span><Action run={async form=>{const f=fields(form);await dataClient.put('/settings/ai/'+p.id,{...f,enabled:f.enabled==='on',preferred:f.preferred==='on',clear_key:f.clear_key==='on'});await qc.invalidateQueries({queryKey:['managed-ai']});await qc.invalidateQueries({queryKey:['ai-status']})}}><label>מפתח API חדש<input name="api_key" type="password" autoComplete="off" maxLength={500} placeholder="השאירי ריק כדי לשמור את המפתח הקיים"/></label><label><input type="checkbox" name="clear_key"/> מחיקת המפתח האישי השמור</label><label>מודל לתמלול<input name="transcription_model" dir="ltr" defaultValue={p.transcription_model} required maxLength={120}/></label><label>מודל לסיכום<input name="summary_model" dir="ltr" defaultValue={p.summary_model} required maxLength={120}/></label>{p.id==='gemini'&&<small>ב־Gemini יש לבחור אותו מודל בשני השדות.</small>}<label><input type="checkbox" name="enabled" defaultChecked={p.enabled}/> הפעלת הספק עבורי</label><label><input type="checkbox" name="preferred" defaultChecked={p.preferred}/> ספק מועדף</label></Action>{p.configured&&<details><summary>בדיקת החיבור שנשמר</summary><Action button="בדיקת חיבור" run={async form=>(await dataClient.post('/settings/ai/'+p.id+'/test',fields(form))).data.message}><p>הבדיקה קוראת לרשימת המודלים בלבד ואינה שולחת תיעוד תלמידות. היא אינה בודקת הרשאה לעיבוד.</p></Action></details>}</section>
}
function ProvidersPanel(){const q=useQuery({queryKey:['managed-ai'],queryFn:async()=>(await dataClient.get<Provider[]>('/settings/ai')).data});return <><AISettings/><p className="card">המפתחות האישיים נשמרים מוצפנים בשרת ואינם מוחזרים לממשק. הגדרה אישית גוברת על הגדרות השרת עבור אותו ספק. הגדרות הסכמה ובדיקת טיוטות נשארות בתוקף. השאירי ספק אישי כבוי כדי לחסום אותו עבורך.</p>{q.error&&<p className="error" role="alert">{errorMessage(q.error)}</p>}{q.data?.map(p=><ProviderForm key={p.id+JSON.stringify(p)} p={p}/>)}</>}
function BackupsPanel({info}:{info:Security}){
 const qc=useQueryClient(),[file,setFile]=useState<File|null>(null)
 const stale=!info.last_backup||Date.now()-new Date(info.last_backup).getTime()>7*24*3600000
 return <><section className="card"><span className="eyebrow">רצף וביטחון</span><h2>גיבוי מוצפן</h2><p>יצירת גיבוי אחרונה: {info.last_backup?new Date(info.last_backup).toLocaleString('he-IL'):'טרם נוצר גיבוי'}</p>{stale&&<p role="status" className="backup-reminder">מומלץ ליצור גיבוי — לא נוצר גיבוי בשבוע האחרון.</p>}<p>הגיבוי כולל כרטיסים בבעלותך, פגישות, משימות ויומן. מפתחות AI, סיסמאות, הגדרות אימות, יומן ביקורת והרשאות שיתוף אינם נכללים. בחרי סיסמת גיבוי נפרדת ושמרי אותה; אין אפשרות לשחזר בלעדיה.</p><Action button="יצירת גיבוי והורדה" run={async form=>{const {data}=await dataClient.post('/settings/backup/export',fields(form));download(JSON.stringify(data),'merhav-backup-'+new Date().toISOString().slice(0,10)+'.json');await qc.invalidateQueries({queryKey:['security']});return 'קובץ מוצפן נוצר. ודאי ששמרת אותו במקום מוגן.'}}><label>סיסמת גיבוי, לפחות 16 תווים<input name="backup_password" type="password" autoComplete="new-password" minLength={16} maxLength={256} required/></label></Action></section><section className="card"><h2>שחזור מגיבוי</h2><p>השחזור מוסיף כרטיסים חדשים לחשבונך. הוא אינו מוחק או מחליף נתונים קיימים, ועלול ליצור תלמידות כפולות. שחזור אותו קובץ פעמיים נחסם.</p><Action button="אישור ושחזור" run={async form=>{if(!file)throw new Error('יש לבחור קובץ גיבוי');if(file.size>15*1024*1024)throw new Error('הקובץ גדול מדי');let archive;try{archive=JSON.parse(await file.text())}catch{throw new Error('קובץ הגיבוי אינו JSON תקין')}const f=fields(form);const {data}=await dataClient.post('/settings/backup/restore',{...f,archive,confirmed:f.confirmed==='on'});await qc.invalidateQueries({queryKey:['students']});await qc.invalidateQueries({queryKey:['appointments']});await qc.invalidateQueries({queryKey:['tasks']});return data.message}}><label>קובץ גיבוי מוצפן<input type="file" accept=".json,application/json" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>סיסמת הגיבוי<input name="backup_password" type="password" minLength={16} maxLength={256} required autoComplete="off"/></label><label><input name="confirmed" type="checkbox" required/> אני מאשרת הוספת כרטיסים חדשים, ללא שיתוף אוטומטי.</label></Action></section></>
}
type ManagedUser={id:string;name:string;email:string;active:boolean;role:string;mfa_enabled:boolean}
export function UsersPanel(){const qc=useQueryClient();const q=useQuery({queryKey:['managed-users'],queryFn:async()=>(await dataClient.get<ManagedUser[]>('/admin/users')).data});return <><section className="card"><h2>הוספת משתמשת מורשית</h2><Action button="יצירת משתמשת" run={async form=>{await dataClient.post('/admin/users',fields(form));await qc.invalidateQueries({queryKey:['managed-users']})}}><label>שם<input name="name" required maxLength={120}/></label><label>מייל<input name="email" type="email" required maxLength={254}/></label><label>סיסמה התחלתית<input name="new_password" type="password" autoComplete="new-password" required minLength={12} maxLength={256}/></label><label>תפקיד<select name="role"><option value="counselor">יועצת</option><option value="admin">מנהלת מערכת</option></select></label></Action></section>{q.error&&<p className="error" role="alert">{errorMessage(q.error)}</p>}{q.data?.map(u=><section key={u.id+JSON.stringify(u)} className="card"><h3>{u.name}</h3><p dir="ltr">{u.email}</p><span className="badge">{u.mfa_enabled?'אימות דו־שלבי פעיל':'אימות דו־שלבי כבוי'}</span><Action run={async form=>{const f=fields(form);await dataClient.patch('/admin/users/'+u.id,{...f,active:f.active==='on'});if(u.id===useAuth.getState().user?.id){useAuth.getState().clear();qc.clear();return}await qc.invalidateQueries({queryKey:['managed-users']});return 'עודכן. ההתחברויות הקודמות של המשתמשת בוטלו.'}}><label><input name="active" type="checkbox" defaultChecked={u.active}/> חשבון פעיל</label><label>תפקיד<select name="role" defaultValue={u.role}><option value="counselor">יועצת</option><option value="admin">מנהלת מערכת</option></select></label><label>סיסמה חדשה, רק לאיפוס<input type="password" name="new_password" autoComplete="new-password" minLength={12} maxLength={256}/></label></Action></section>)}</>}
export function Management(){const [tab,setTab]=useState('security');const q=useQuery({queryKey:['security'],queryFn:async()=>(await dataClient.get<Security>('/settings/security')).data,refetchOnWindowFocus:false,refetchOnReconnect:false});const tabs=[['security','אבטחה'],['ai','ספקי AI'],['backups','גיבוי ושחזור'],...(q.data?.role==='admin'?[['users','משתמשות והרשאות']]:[])];return <><header><span className="eyebrow">המערכת שלך</span><h1>הגדרות וניהול</h1><p>הגדרות אישיות, שמירת המידע וגישה מורשית.</p></header><nav className="settings-tabs" aria-label="תחומי הגדרות">{tabs.map(([id,label])=><button key={id} className={tab===id?'':'secondary'} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>{q.error&&<p role="alert" className="error">{errorMessage(q.error)}</p>}{q.isPending?<p>טוענת הגדרות…</p>:q.data&&<>{tab==='security'&&<SecurityPanel info={q.data}/ >}{tab==='ai'&&<ProvidersPanel/>}{tab==='backups'&&<BackupsPanel info={q.data}/ >}{tab==='users'&&q.data.role==='admin'&&<UsersPanel/>}</>}</>}
export function Sharing({studentId}:{studentId:string}){
 const qc=useQueryClient();const q=useQuery({queryKey:['shares',studentId],queryFn:async()=>(await dataClient.get<{id:string;name:string;email:string}[]>('/students/'+studentId+'/shares')).data});const directory=useQuery({queryKey:['directory'],queryFn:async()=>(await dataClient.get<{id:string;name:string;email:string}[]>('/directory')).data});return <section className="card"><h2>שיתוף כרטיס עם יועצת</h2><p>השיתוף מאפשר צפייה בפרטי הכרטיס, בפגישות, במשימות וביומן. רק את יכולה לערוך או לשתף הלאה. ודאי שהיועצת מורשית לקבל את התיעוד.</p><Action button="שיתוף לצפייה" run={async form=>{await dataClient.post('/students/'+studentId+'/shares',fields(form));await qc.invalidateQueries({queryKey:['shares',studentId]})}}><label>יועצת<select name="user_id" required><option value="">בחרי יועצת</option>{directory.data?.map(u=><option value={u.id} key={u.id}>{u.name} — {u.email}</option>)}</select></label></Action>{(q.error||directory.error)&&<p role="alert" className="error">{errorMessage(q.error||directory.error)}</p>}{q.data?.map(u=><details key={u.id}><summary>{u.name} — {u.email} • הרשאת צפייה</summary><Action button="ביטול שיתוף" run={async form=>{await dataClient.post('/students/'+studentId+'/shares/'+u.id+'/revoke',fields(form));await qc.invalidateQueries({queryKey:['shares',studentId]})}}><p>ביטול ההרשאה נכנס לתוקף בבקשות הבאות לשרת.</p></Action></details>)}</section>
}
