import { useEffect, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { dataClient, errorMessage } from './api/http'
export function Recorder({studentId,onTranscript,onSummary,onBusy}:{studentId:string;onTranscript:(text:string)=>void;onSummary:(text:string)=>void;onBusy:(busy:boolean)=>void}) {
 const status=useQuery({queryKey:['ai-status'],queryFn:async()=>(await dataClient.get<{enabled:boolean;message:string}>('/ai/status')).data})
 const [consent,setConsent]=useState(false),[phase,setPhase]=useState('idle'),[elapsed,setElapsed]=useState(0),[audio,setAudio]=useState<Blob|null>(null),[transcript,setTranscript]=useState(''),[error,setError]=useState<unknown>(null)
 const media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),parts=useRef<Blob[]>([]),mounted=useRef(true),abort=useRef<AbortController|null>(null),starting=useRef(false)
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abort.current?.abort();if(media.current?.state!=='inactive')media.current?.stop();stream.current?.getTracks().forEach(t=>t.stop());parts.current=[]}},[])
 useEffect(()=>{onBusy(['starting','recording','paused','processing'].includes(phase))},[phase,onBusy])
 useEffect(()=>{if(phase!=='recording')return;const timer=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(timer)},[phase])
 useEffect(()=>{if(elapsed>=600 && media.current?.state==='recording')media.current.stop()},[elapsed])
 useEffect(()=>{if(!['starting','recording','paused','processing'].includes(phase))return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[phase])
 async function start(){if(!consent||starting.current)return;starting.current=true;setError(null);setPhase('starting');try{
  if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw Error('unsupported')
  const mic=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){mic.getTracks().forEach(t=>t.stop());return}stream.current=mic
  const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('unsupported')
  const recorder=new MediaRecorder(mic,{mimeType:mime});media.current=recorder;parts.current=[];setAudio(null);setTranscript('');setElapsed(0)
  recorder.ondataavailable=e=>{if(e.data.size)parts.current.push(e.data);if(parts.current.reduce((n,b)=>n+b.size,0)>20*1024*1024&&recorder.state!=='inactive')recorder.stop()}
  recorder.onstop=()=>{mic.getTracks().forEach(t=>t.stop());if(!mounted.current)return;const blob=new Blob(parts.current,{type:mime});parts.current=[];if(blob.size>20*1024*1024){setError(Error('large'));setPhase('idle');return}setAudio(blob);setPhase('ready')}
  recorder.onerror=()=>{mic.getTracks().forEach(t=>t.stop());if(mounted.current){setError(Error('recording'));setPhase('idle')}}
  recorder.start(1000);setPhase('recording')
 }catch{stream.current?.getTracks().forEach(t=>t.stop());if(mounted.current){setError(Error('microphone'));setPhase('idle')}}finally{starting.current=false}}
 async function transcribe(){if(!audio||!consent)return;setPhase('processing');setError(null);abort.current=new AbortController();try{const {data}=await dataClient.post(`/ai/students/${studentId}/transcribe`,audio,{headers:{'Content-Type':audio.type,'X-Recording-Consent':'true'},timeout:180000,signal:abort.current.signal});if(mounted.current){setTranscript(data.transcript);onTranscript(data.transcript);setPhase('ready')}}catch(e){if(mounted.current){setError(e);setPhase('ready')}}}
 async function summarize(){if(!consent||!transcript.trim())return;setPhase('processing');setError(null);abort.current=new AbortController();try{const {data}=await dataClient.post(`/ai/students/${studentId}/summarize`,{transcript,consent:true},{timeout:180000,signal:abort.current.signal});if(mounted.current){onSummary(data.summary);setPhase('ready')}}catch(e){if(mounted.current){setError(e);setPhase('ready')}}}
 useEffect(()=>{if(!['starting','recording','paused','processing'].includes(phase))return;const guard=(e:MouseEvent)=>{const anchor=(e.target as Element).closest?.('a[href]');if(anchor&&!window.confirm('המעבר יפסיק את ההקלטה או העיבוד וטיוטה שלא נשמרה תאבד. להמשיך?')){e.preventDefault();e.stopPropagation()}};document.addEventListener('click',guard,true);return()=>document.removeEventListener('click',guard,true)},[phase])
 const locked=['starting','recording','paused','processing'].includes(phase)
 return <section className="card"><h3>הקלטה, תמלול וסיכום</h3>{!status.data?.enabled?<p>{status.data?.message||'בודקת זמינות AI…'}</p>:<><p>ההקלטה או התמלול יישלחו ל־OpenAI לעיבוד. יש לוודא שההסכמה הנדרשת תועדה לפי מדיניות המוסד. השמע אינו נשמר במערכת; לספק יש מדיניות שמירה משלו.</p><label><input type="checkbox" checked={consent} disabled={locked||Boolean(audio)||Boolean(transcript)} onChange={e=>setConsent(e.target.checked)}/> תיעדתי הסכמה להקלטה ולעיבוד ב־AI</label><div className="row"><button type="button" disabled={!consent||locked||Boolean(audio)} onClick={start}>התחלת הקלטה</button>{(phase==='recording'||phase==='paused')&&<><span role="status">{phase==='paused'?'מושהית':'מקליטה'} • {Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</span><button type="button" className="secondary" onClick={()=>{if(phase==='recording'){media.current?.pause();setPhase('paused')}else{media.current?.resume();setPhase('recording')}}}>{phase==='paused'?'המשך':'השהיה'}</button><button type="button" onClick={()=>media.current?.stop()}>עצירה</button></>}</div>{audio&&<div className="row"><p>הקלטה מוכנה • עד 10 דקות ו־20MB</p><button type="button" disabled={locked||!consent||Boolean(transcript)} onClick={transcribe}>תמלול לעברית</button><button type="button" className="secondary" disabled={locked} onClick={()=>{setAudio(null);setPhase('idle')}}>מחיקת ההקלטה</button></div>}<label>תמלול לבדיקה ועריכה<textarea value={transcript} maxLength={20000} rows={6} disabled={locked||!consent} onChange={e=>{setTranscript(e.target.value);onTranscript(e.target.value)}}/></label><button type="button" disabled={locked||!consent||!transcript.trim()} onClick={summarize}>יצירת טיוטת סיכום</button>{phase==='processing'&&<p role="status">מעבדת… ניתן לתקן את התוצר לפני שמירה.</p>}</>}{status.error&&<p role="alert" className="error">{errorMessage(status.error)}</p>}{Boolean(error)&&<p role="alert" className="error">{error instanceof Error&&!('isAxiosError' in error)?'ההקלטה לא הצליחה. בדקי הרשאת מיקרופון, תמיכת הדפדפן ומגבלת הגודל.':errorMessage(error)}</p>}</section>
}
